# Generated by Django 6.0.1 on 2026-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='cursando_licencia_anual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licencia',
            name='domicilio',
            field=models.CharField(blank=True, default='', help_text='Domicilio real durante la licencia', max_length=255),
        ),
        migrations.AddField(
            model_name='licencia',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', help_text='Email de contacto', max_length=254),
        ),
        migrations.AddField(
            model_name='licencia',
            name='es_internacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='iniciada', help_text='Estado real en base de datos (obsoleto, se calcula en estado_actual)', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('personal', 'Personal'), ('rrhh', 'Recursos Humanos'), ('bienestar', 'Bienestar')], default='personal', max_length=20),
        ),
    ]
