# Generated by Django 6.0.1 on 2026-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_licencia_cursando_licencia_anual_licencia_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='doctor_nombre',
            field=models.CharField(default='', help_text='Nombre del doctor que emite el certificado', max_length=200),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo_atencion',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('telemedicina', 'Telemedicina')], default='presencial', max_length=20),
        ),
    ]
